In [4]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

In [32]:
df = pd.read_csv('../src/data/diabetes.csv')
df

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0              6      148         72       35        0  33.6  0.627   50   
1              1       85         66       29        0  26.6  0.351   31   
2              8      183         64        0        0  23.3  0.672   32   
3              1       89         66       23       94  28.1  0.167   21   
4              0      137         40       35      168  43.1  2.288   33   
..           ...      ...        ...      ...      ...   ...    ...  ...   
763           10      101         76       48      180  32.9  0.171   63   
764            2      122         70       27        0  36.8  0.340   27   
765            5      121         72       23      112  26.2  0.245   30   
766            1      126         60        0        0  30.1  0.349   47   
767            1       93         70       31        0  30.4  0.315   23   

     diabetes  
0           1  
1           0  
2           1  
3           0  
4           1  
..        ...  
763         0  
764         0  
765         0  
766         1  
767         0  

[768 rows x 9 columns]

In [10]:
# make a dataframe without the diabetes column
# because that is what we are trying to predict

x = df.drop(columns=['diabetes'])

x.head()



pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
0            6      148         72       35        0  33.6  0.627   50
1            1       85         66       29        0  26.6  0.351   31
2            8      183         64        0        0  23.3  0.672   32
3            1       89         66       23       94  28.1  0.167   21
4            0      137         40       35      168  43.1  2.288   33

In [13]:
## insert diabetes column into target variable
y = df['diabetes'].values

y[:10]

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1])

In [16]:
# dope lets split the data
# into a training and test set

from sklearn.model_selection import train_test_split
# lets split this shit
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1, stratify=y)




In [18]:
# ok let's build and train the model
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)

# the fit function is what trains up the model
knn.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=3)

In [22]:
# time to test

#print(X_test[0:10])

knn.predict(X_test)[0:10]

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0])

In [23]:
#scoring the model
knn.score(X_test, y_test)

0.6688311688311688

In [25]:
## cross fold validation

from sklearn.model_selection import cross_val_score
import numpy as np

# create a new model
knn_cv = KNeighborsClassifier(n_neighbors=3)

#train with cross calidation of 5
cv_scores = cross_val_score(knn_cv, x, y, cv=5)

# print each cv score (accuracy) and average them

print(cv_scores)
print(f"cv_scores mean: {np.mean(cv_scores)}")

[0.68181818 0.69480519 0.75324675 0.75163399 0.68627451]
cv_scores mean: 0.7135557253204311


In [28]:
from sklearn.model_selection import GridSearchCV

## one more new model
knn2 = KNeighborsClassifier()

#dictionary of all values to test fo rn_negightbors

param_grid = {'n_neighbors':np.arange(1,25)}

# use grid search to test all values for n_neighbors
knn_gscv = GridSearchCV(knn2, param_grid, cv=5)

## runt he model by fitting it 

knn_gscv.fit(x,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])})

In [29]:
# check which params did the best

knn_gscv.best_params_

{'n_neighbors': 14}

In [30]:
knn_gscv.best_score_

0.7578558696205755